### ISSUE TITLE
Make heartbeat track get louder for low health/tense fights

### ISSUE THREAD

**Issue by DLMcPherson** [ehgoodenough/gmtk-2017#19]
The heartbeat track is loaded as an independent audio track so that it's volume can be independently controlled to signal important moments such as low health. Just turn up the volume when the player's total hearts are below a certain threshhold.

**Comment by DLMcPherson** [comment]
I tried to do this by adding a routine in the player class that checks for low health and changes the volume appropriately via Jukebox.heartbeat.volume. Unfortunately, I can't hear any difference. There must be something I don't understand about volumes and audio in JavaScript... :/

**Comment by ehgoodenough** [comment]
I'll take a look at it, if possible

**Comment by ehgoodenough** [comment]
Yeah, I couldn't get this to work, either. I tried mixing it so the music got quieter as the heart-beat got louder, that didn't sound good at all.
