### ISSUE TITLE
A sound should play whenever a bullet connects with a baddie.

### ISSUE THREAD

**Issue by ehgoodenough** [ehgoodenough/gmtk-2017#23]

**Comment by DLMcPherson** [comment]
I'm leaving this one to you since I don't know how you designed the previous sound effects and they sound good. :)
     When you make an impact sound for the baddies could you add it to the impact sound for when a baddie bullet hits the player? Right now it's the pickup "pprring!" which is too happy for a bad thing like losing health.

**Comment by DLMcPherson** [comment]
Also, should the baddies make a sound when they fire? I had them playing the hero's shooting sound originally, but that got annoying since there were so many of them shooting nonstop bullets.

**Comment by ehgoodenough** [comment]
http://github.grumdrig.com/jsfxr/
