### ISSUE TITLE
Rip hearts out of enemies

### ISSUE THREAD

**Issue by DLMcPherson** [ehgoodenough/gmtk-2017#37]

**Comment by ehgoodenough** [comment]
I can't believe we finished this in time 0.o

**Comment by DLMcPherson** [comment]
Yeah, I spent way more time than I should've animating those dudes. Getting the heart to display above his hand was also giving me trouble. Just like displaying the tree at the end, I apparently don't know how to make sprites appear right. I got it in the end by randomly trying different things :/
