### ISSUE TITLE
Record and add voice stabs

### ISSUE THREAD

**Issue by DLMcPherson** [ehgoodenough/gmtk-2017#39]
Including, but not limited to:

* "HAVE A HEAARRT!!"
* "CROSS MY HEAART, HOPE YOU DIE!"
* "BLESS HER HEAAARRRT"
* "I JUST LOVE YOU TO DEATH!"
* "I WILL WEAR /YOUR/ HEART ON MY SLEEVE!"

**Comment by ehgoodenough** [comment]
They're campy, but they're there :D
