### ISSUE TITLE
Write some music!

### ISSUE THREAD

**Issue by ehgoodenough** [ehgoodenough/gmtk-2017#9]
At the moment, I'm just stealing [Toni Ley's Procrastinator Elevator](https://www.youtube.com/watch?v=danoWwT2HLg). Which, although very catchy, is not ours, so we can't use it for the jam. We'll need to write something ourselves if we want music.

(Which is probably for the best; `procrastinator-elevator.mp3` doesn't really fit the action fast-paced mood of the game. It feels like it belongs in Pokemon or something.)

When you write some music, drop it into `source/music`, and `require` it in `scripts/index.js`. You'll see we have a `Jukebox` class, which takes an array of Audio instances. Add your music here:

```js
var jukebox = new Jukebox([
    new Audio(require("music/name-of-your-music.mp3")),
    new Audio(require("music/name-of-your-second-music.mp3")),
])
```

To hear your songs, be sure to go to  http://localhost:8080/?stage=production; that query flag sets the `STAGE` to `"PRODUCTION"`, so the jukebox will play. I've turned it off in the development stage, since otherwise I might get sick of the song from hearing them play over and over while I'm developing.

The jukebox will loop through each of the songs in the array, so if you'd rather write multiple shorter songs, the jukebox can handle that for you.

Most browsers support mp3, and although some others also support wav or ogg, we should only write in mp3 so we can have the most compatibility with browsers.

**Comment by DLMcPherson** [comment]
Done-zo, babe!
